// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6rJu93Dvzy4PcCX888YsOAwbw5n-2mN4',
    appId: '1:392019569811:web:9f1f51bd7394b2ded93166',
    messagingSenderId: '392019569811',
    projectId: 'the-armor-of-god',
    authDomain: 'the-armor-of-god.firebaseapp.com',
    storageBucket: 'the-armor-of-god.appspot.com',
    measurementId: 'G-72W2J4ZW9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLKV07sc6OVN6QBhSyiHbS3jJXUYpP1bs',
    appId: '1:392019569811:android:fcabeb989ab03180d93166',
    messagingSenderId: '392019569811',
    projectId: 'the-armor-of-god',
    storageBucket: 'the-armor-of-god.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD25bvw5eombiE-fQLFHd79mllUp84WZ9k',
    appId: '1:392019569811:ios:be69e0cd489fd8bbd93166',
    messagingSenderId: '392019569811',
    projectId: 'the-armor-of-god',
    storageBucket: 'the-armor-of-god.appspot.com',
    iosClientId:
        '392019569811-0hcpe2onvjb5kh82iaf51g58d2j0f1ns.apps.googleusercontent.com',
    iosBundleId: 'com.example.armorOfGod',
  );
}
